makeitfresh/shopproject/main/routes.py
from flask import render_template, Blueprint, request, json, redirect, url_for
from flask_login import login_required, current_user
from shopproject.models import Shop
from sqlalchemy import or_
main = Blueprint('main', __name__)

@main.after_request
def add_header(r):
    r.headers.add('Cache-Control', 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0')
    return r


@main.route("/")
@main.route("/home")
@login_required
def home():
    if current_user.email_verified:
        if current_user.user_type == "buyer":
            search_entry = request.args.get("shop")
            if request.args.get("shop"):
                shops = []
                for shop in Shop.query.filter(or_(
                    Shop.name.startswith(search_entry.lower()),
                    Shop.name.startswith(search_entry.upper()),
                    Shop.name.startswith(search_entry)
                    )).all():
                    shops.append({
                        "name":shop.name.lower(),
                        "phone_number":shop.phone_number,
                    })
                return json.jsonify(shops)
        return render_template("main/buyer.html")
    else:
        return render_template("users/test_email_verif_hint.html")
    return render_template("main/home.html")

@main.route("/buyerhome")
def BuyerHome():
    return render_template("homebuyer.html")

makeitfresh/shopproject/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, Response, abort, session
from flask_login import login_user, current_user, logout_user, login_required
from is_safe_url import is_safe_url
from shopproject import db, bcrypt
from shopproject.models import User
from shopproject.users.forms import UserRegistrationForm, LoginForm, ResetPasswordForm, RequestResetForm
from shopproject.users.utils import send_pwd_reset_email, send_email_verif
from sqlalchemy import or_

users = Blueprint('users', __name__)

@users.after_request
def add_header(r):
    r.headers.add('Cache-Control', 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0')
    return r


@users.route("/register",methods=['POST','GET'])
def userRegistration():
    form=UserRegistrationForm()
    if current_user.is_authenticated:
            return redirect(url_for('main.home'))
    elif request.method=="POST" and form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        new_user = User(
            user_type=form.user_type.data,
            username=form.username.data.strip(),
            email=form.email.data.strip(),
            first_name=form.first_name.data.strip(),
            last_name=form.last_name.data.strip(),
            password=hashed_password,
        )
        db.session.add(new_user)
        db.session.commit()
        if new_user:
            token = new_user.get_reset_token()
            url = url_for("users.verify_email", token = token, _external=True)
            send_email_verif(new_user.email, url)
            flash(f"Your account has been created.An email has been sent to your inbox. Please verify your email to access the website.", 'success')
        else:
            flash(f"Sorry your account has not been created. Please retry.")
        return redirect(url_for('users.login'))
    elif request.method == "POST" and (not form.validate_on_submit()):
        flash(f'Please correct the incorrect fields.')
    return render_template("users/register.html", title="Register", form=form)



@users.route("/login",methods=['POST', 'GET'])
def login():
    form=LoginForm()
    if current_user.is_authenticated:
            return redirect(url_for('main.home'))
    elif form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            user.authenticated = True
            login_user(user, remember=form.remember.data)

            next_page= request.args.get('next')
            if next_page and not is_safe_url(next_page, allowed_hosts={"127.0.0.1:5000"}):
                return abort(400)
            flash(f'Login successful. Welcome {user.username}!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        
        else:
            flash(f'Login unsuccessful. Check username and password ','danger')
    return render_template('users/login.html',title="Login",form=form)


@users.route("/logout")
@login_required
def logout():
    user = User.query.get(current_user.id)
    user.authenticated=False
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account")
@login_required
def account():
    if not current_user.email_verified:
        return redirect(url_for("main.home"))
    return render_template("users/account.html", title="Account")

#Not completeauthenticated
@users.route("/reset_password", methods=["GET", "POST"])
def request_reset_password():
    form = RequestResetForm()
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    else:
        if form.validate_on_submit() and request.method == "POST":
            user = User.query.filter_by(email=form.email.data).first()
            if user:
                recipient_email = user.email
                token = user.get_reset_token()
                url = url_for("users.reset_password_token", token = token, _external=True)
                send_pwd_reset_email(recipient_email, url)
                flash(f"Please check your inbox for steps to reset your password." ,"info")
                return redirect(url_for("main.home"))
            else:
                flash(f"User does not exist.", "failure")
    return render_template("users/test_request_reset.html", form=form)

#Not complete
@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password_token(token):
    form = ResetPasswordForm()
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "danger")
        return redirect(url_for("users.request_reset_password"))
    else:
        if form.validate_on_submit() and request.method == "POST":
            user.password = bcrypt.generate_password_hash(form.new_password.data).decode("utf-8")
            db.session.commit()
            flash(f"Password has been reset successfully. You may now login.", "success")
            return redirect(url_for("users.login"))

    return render_template("users/test_reset_password.html", form=form, token=token)


@users.route("/verif_email/<token>") 
def verify_email(token):
    if current_user.is_authenticated and current_user.email_verified:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "danger")
        return
    else:
        user.email_verified = True
        db.session.commit()
        if request.method == "GET" and current_user==user:
            flash("Your account has been activated.", "success")
            return redirect(url_for("main.home"))
        elif current_user != user:
            flash("Your account has been activated. Please login to continue", "success")
            return redirect(url_for("users.login"))

            

makeitfresh/shopproject/templates/ShopRegister.html
{% extends "layout.html" %}
{% block content %}
<div >
    <div class="page-content">
        <div class="container-fluid loginbox ">
            <div class="row justify-content-center">
                <div class="col-6 col-md-4">
                    <form class="form-container" id="form" method="POST" action="">
                        {{form.hidden_tag()}}
                        <fieldset class="loginbox">
                            <h1 class="heading">Register Your Shop</h1>

                                    

                                    <div class="form-group">
                                        {{form.username.label(class="label")}}<br/>
                                        {% if form.username.errors %}
                                            {{form.username(class="form-control input is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.username.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{form.username(class="form-control input")}}
                                        {% endif %}
                                    </div>
                                
                                
                                    <div class="form-group">
                                        {{form.email.label(class="label")}}<br/>
                                        {% if form.email.errors %}
                                            {{form.email(class="form-control input is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.email.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{form.email(class="form-control input")}}
                                        {% endif %}
                                    </div>
                                
                                
                                
                                    <div class="form-group">
                                        {{form.password.label(class="label")}}<br/>
                                        {% if form.password.errors %}
                                            {{form.password(class="form-control input is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.password.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{form.password(class="form-control input")}}
                                        {% endif %}
                                    </div>
                                
                                
                                    <div class="form-group">
                                        {{form.confirm_password.label(class="label")}}<br/>
                                        {% if form.confirm_password.errors %}
                                            {{form.confirm_password(class="form-control input is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.confirm_password.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{form.confirm_password(class="form-control input")}}
                                        {% endif %}
                                    </div>
                                
                                
                                    <div class="form-group">
                                        {{form.shopname.label(class="label")}}<br/>
                                        {% if form.shopname.errors %}
                                            {{form.shopname(class="form-control input is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.shopname.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{form.shopname(class="form-control input")}}
                                        {% endif %}
                                    </div>
                                
                                    <div class="form-group">
                                        {{form.propreitername.label(class="label")}}<br/>
                                        {% if form.propreitername.errors %}
                                            {{form.propreitername(class="form-control input is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.propreitername.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{form.propreitername(class="form-control input")}}
                                        {% endif %}
                                    </div>
                                
                                    <div class="form-group">
                                        {{form.mobilenumber.label(class="label")}}<br/>
                                        {% if form.mobilenumber.errors %}
                                            {{form.mobilenumber(class="form-control input is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.mobilenumber.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{form.mobilenumber(class="form-control input")}}
                                        {% endif %}
                                    </div>
                                
                                    <div class="form-group">
                                        {{form.place.label(class="label")}}<br/>
                                        {% if form.place.errors %}
                                            {{form.place(class="form-control input is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.place.errors %}
                                                    <span class="display-error">{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{form.place(class="form-control input")}}
                                        {% endif %}
                                    </div>       
                            <div >
                                {{form.submit(class='button btn btn-primary btn-block')}}
                            </div>
                            <div ><br/><small>Already Have an Account? <a href="#">Login</a></small></div>
                        </fieldset>

                    </form>
                </div>    
            </div>        
        </div>            
    </div>                
</div>



{% endblock content %}

makeitfresh/shopproject/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{{url_for('static',filename='styles/bootstrap.min.css')}}" type="text/css">
  <link rel="stylesheet" href="{{url_for('static',filename='styles/main.css')}}" type="text/css">
  <!--bootstrap 3-->
  {% if title %}
  <title>MakeItFresh-{{title}}</title>
  {%else%}
  <title>MakeItFresh</title>
  {% endif %}
</head>

<body class="d-flex flex-column">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <span class="navbar-brand mb-0 h1">MakeItFresh</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('main.home')}}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link">About Us</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
        </li>
        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.userRegistration')}}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </nav>
  <div class="page-content">
    <div>
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      {% if category == 'message' %}
      <div class="alert alert-warning" role="alert">
        {% else %}
        <div class="alert alert-{{ category }}" role="alert">
          {% endif %}
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
      </div>
      {% block content %}
      {% endblock content %}
    </div>


  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="{{url_for('static', filename='scripts/bootstrap.min.js')}}"></script>

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <!--script for font awesome-->
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  {% block scripts %}
  {% endblock scripts %}





</body>

</html>

makeitfresh/shopproject/templates/mainhome.html
{% extends "layout.html" %}
{% block content %}
        <div class="container">
            <h1>Home Page</h1>

        </div>
 {% endblock content %}   
 

makeitfresh/shopproject/templates/old_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{{url_for('static',filename='main.css')}}">
  <!--bootstrap 3-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  {% if title %}
  <title>MakeItFresh-{{title}}</title>
  {%else%}
  <title>MakeItFresh</title>
  {% endif %}
</head>

<body class="d-flex flex-column">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <span class="navbar-brand mb-0 h1">MakeItFresh</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('main.home')}}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">About Us</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
        </li>
        {% else %}
        
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.userRegistration')}}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
        </li>
        {% endif %}
        
      </ul>
    </div>
  </nav>
  <div>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'message' %}
    <div class="alert alert-warning" role="alert">
      {% else %}
      <div class="alert alert-{{ category }}" role="alert">
        {% endif %}
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
    </div>
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
</body>

</html>